# You will need to replace the variables in this file with your specifics for your target server. 
# This will be for client-side node that is being monitored by Grafana node

# This user will will for node_exporter Dashboard by Prometheus
node_exporter_user: node_exporter