# You will need to replace the variables in this file with your specifics for your target server. 
# This will be for Grafana monitoring node

prometheus_user: prometheus
node_exporter_user: node_exporter