---
- hosts: all
  tasks:
    - name: Ping all Hosts
      ping: ""

- hosts: monitoring_node
  tasks:
    - name: Ping "monitoring_node" Hosts
      ping: ""

- hosts: client_nodes
  tasks:
    - name: Ping "client_nodes" Hosts
      ping: ""

- hosts: localhost
  tasks:
    - name: Ping "ctrl-ansible" locally
      ping: ""