---
#- hosts: all
#  tasks:
#    - name: Ping all Hosts
#      ping: ""

- hosts: monitoring_node
  tasks:
    - name: Ping "monitoring_node" Hosts
      ping: ""

- hosts: client_node_fqdn
  tasks:
    - name: Ping "client_node_fqdn" Hosts
      ping: ""
